### ISSUE TITLE
Not working for go 1.18

### ISSUE THREAD

**Issue by mkaratekin** [couchbase/gocb-opentelemetry#6] opened 2022-07-29 09:32 UTC
Hi, 

It didn't work for go 1.18. 

`../../go/pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.0/metrics.go:35:35: meter.wrapped.NewInt64Counter undefined (type metric.Meter has no field or method NewInt64Counter)
../../go/pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.0/metrics.go:59:36: meter.wrapped.NewInt64ValueRecorder undefined (type metric.Meter has no field or method NewInt64ValueRecorder)
../../go/pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.0/metrics.go:79:17: undefined: metric.Int64Counter
../../go/pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.0/metrics.go:82:66: undefined: metric.Int64Counter
../../go/pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.0/metrics.go:95:17: undefined: metric.Int64ValueRecorder
../../go/pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.0/metrics.go:98:78: undefined: metric.Int64ValueRecorder
../../go/pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.0/tracing.go:59:39: undefined: attribute.Any`

**Comment by chvck** [comment] 2022-08-10 07:21
Hi @mkaratekin I've just cut a new release which contains a fix made back in March. I believe that this should address this issue. Please reopen this issue if you continue to see issues.

**Comment by tony-clarke-amdocs** [comment] 2022-09-13 02:17
@chvck I just tried using version [v0.1.1](https://github.com/couchbase/gocb-opentelemetry/releases/tag/v0.1.1) and got the exact same error. I was using 1.18.2

**Comment by chvck** [comment] 2022-09-13 08:08
Hi @tony-clarke-amdocs could you post the stacktrace that you see please? Parts of the above stacktrace don't actually make sense for the v0.1.1 tag.

**Comment by tony-clarke-amdocs** [comment] 2022-09-13 12:53
Hi @chvck 
You are right it's a little different...

github.com/couchbase/gocb-opentelemetry
../../../../pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.1/metrics.go:35:35: meter.wrapped.NewInt64Counter undefined (type metric.Meter has no field or method NewInt64Counter)
../../../../pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.1/metrics.go:60:36: meter.wrapped.NewInt64Histogram undefined (type metric.Meter has no field or method NewInt64Histogram)
../../../../pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.1/metrics.go:79:20: undefined: metric.Int64Counter
../../../../pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.1/metrics.go:83:66: undefined: metric.Int64Counter
../../../../pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.1/metrics.go:97:20: undefined: metric.Int64Histogram
../../../../pkg/mod/github.com/couchbase/gocb-opentelemetry@v0.1.1/metrics.go:101:78: undefined: metric.Int64Histogram
make: *** [build] Error 2

**Comment by chvck** [comment] 2022-09-29 09:36
Hi @tony-clarke-amdocs we're unable to reproduce this, are you able to share a sample project or similar?

**Comment by tony-clarke-amdocs** [comment] 2022-09-29 11:55
@chvck the current project is protected by company IP. If I get time I will try to reproduce independently.

**Comment by chvck** [comment] 2024-03-12 14:04
I'm closing as, as far as I'm aware, this is no longer an issue.

**Closed as completed by chvck** 2024-03-12 14:04 UTC
